### ISSUE TITLE
PKG_CHECK_VAR macro fails

### ISSUE THREAD

**Issue by junka** [p11-glue/p11-kit#200]
Since 0.23.13, PKG_CHECK_VAR was introduced, but it fails on most older os version. 
Do you plan to consider adding a PKG_CHECK_VAR.m4  to make the source compatible with older os.

**Comment by ueno** [comment]
I doubt it would be useful because:
- normal users are recommended to build from the released tarballs which doesn't need the macro (because it's inlined in aclocal.m4)
- users bootstrapping from the git wouldn't mind copying the latest `pkg.m4` from the upstream

So I would rather add something like:
```
m4_ifdef([PKG_PREREQ], [PKG_PREREQ(0.29)], [
  [m4_fatal([pkg.m4 is too old; put the latest version in build/m4])])
```

**Comment by Mythracis** [comment]
Excuse me. I'm new to autoconf, but where can I copy the latest pkg.m4?
I tried copying this one (https://github.com/pkgconf/pkgconf/blob/master/pkg.m4) to p11-kit/build/m4 and then run
`./autogen.sh --prefix=$HOME`
but I still got
`configure.ac:35: error: pkg.m4 is too old; copy the latest version in build/m4`

Besides, I actually tried the released tarballs (https://github.com/p11-glue/p11-kit/releases/download/0.25.0/p11-kit-0.25.0.tar.xz) as you recommend to normal users. I did:
`./configure --build=i686-pc-linux-gnu CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 --prefix=$HOME
make
make install`
Everything went well until I got
` /usr/bin/install -c -m 644 bash-completion/p11-kit bash-completion/trust '/usr/share/bash-completion/completions'
/usr/bin/install: cannot create regular file ‘/usr/share/bash-completion/completions/p11-kit’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/share/bash-completion/completions/trust’: Permission denied`
However, I don't have root to this system. Is there a way for me to circumvent this problem? Thank you!

**Comment by ueno** [comment]
https://github.com/pkgconf/pkgconf/blob/master/pkg.m4 seems like the canonical one.

I just tried to reproduce your problem by decreasing the `PKG_MACROS_VERSION` in `/usr/share/aclocal/pkg.m4` and then copying the latest `pkg.m4` in `build/m4`, but it worked as expected. It would be helpful if you could provide the complete log of `autogen.sh`.

**Comment by ueno** [comment]
> `autoreconf: running: aclocal -I <$HOME>/local64/share/aclocal/ --force -I build/m4`

This line is apparently causing the issue, though I'm not sure why this is happening. On my environment it is `autoreconf: running: aclocal --force -I build/m4`.

Is your autotools installation pristine?

I guess a workaround would be to directly call `autoreconf` instead of the autogen.sh script, with `-B`.

**Comment by Mythracis** [comment]
Sorry, `aclocal -I <$HOME>/local64/share/aclocal/` is from my .bashrc for some other package. If I remove that I get
_autoreconf: running: aclocal --force -I build/m4
configure.ac:35: error: pkg.m4 is too old; copy the latest version in build/m4_

I tried direct autoreconf
`autoreconf --install --force --prepend-include=/mnt/mbi/home/mbiwh/wine_lib_src/p11-kit/build/m4`
_autopoint: using AM_GNU_GETTEXT_REQUIRE_VERSION instead of AM_GNU_GETTEXT_VERSION
configure.ac:35: error: pkg.m4 is too old; copy the latest version in build/m4
configure.ac:35: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1_

Is that how -B is supposed to be used?
