### ISSUE TITLE
Homebrew version of p11-kit has incorrect list of certificates 

### ISSUE THREAD

**Issue by kevincianfarini** [p11-glue/p11-kit#404]
### Update

As shown in the below comments, we've narrowed the problem down to a transitive `p11-kit` dependency installed via homebrew. Continued exploration should stem from there. 

I've updated the issue title to reflect this. 

### Original Post 

This issue has now been documented in multiple places, so plenty of context can be found in the following places. 

* https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1358
* https://github.com/flatpak/flatpak/issues/4603

When using Flatpak applications like `com.slack.Slack`, I am unable to retrieve the correct SSL certs to establish an HTTPS connection. Here's a sample of what `gnutls-cli` sees when trying to connect to `app.slack.com`. 

```
flatpak run -d --command=/bin/bash com.slack.Slack
[📦 com.slack.Slack ~]$ which gnutls-cli
/usr/bin/gnutls-cli
[📦 com.slack.Slack ~]$ gnutls-cli app.slack.com
Processed 0 CA certificate(s).
Resolving 'app.slack.com:443'...
Connecting to '54.163.235.119:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=slack.com,O=Slack Technologies\, Inc.,L=San Francisco,ST=California,C=US', issuer `CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US', serial 0x080b9ecfe5023817bf560b76c5526c8b, RSA key 2048 bits, signed using RSA-SHA256, activated `2021-04-13 00:00:00 UTC', expires `2022-04-18 23:59:59 UTC', pin-sha256="eiS4sOaLY6r0bgQtUeUx7BqGmb1JufJmCPueVkT7U0Y="
	Public Key ID:
		sha1:337d31b376b32c22131c3e014c88c9a46af0a2df
		sha256:7a24b8b0e68b63aaf46e042d51e531ec1a8699bd49b9f26608fb9e5644fb5346
	Public Key PIN:
		pin-sha256:eiS4sOaLY6r0bgQtUeUx7BqGmb1JufJmCPueVkT7U0Y=

- Certificate[1] info:
 - subject `CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US', issuer `CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US', serial 0x0a3508d55c292b017df8ad65c00ff7e4, RSA key 2048 bits, signed using RSA-SHA256, activated `2020-09-24 00:00:00 UTC', expires `2030-09-23 23:59:59 UTC', pin-sha256="RQeZkB42znUfsDIIFWIRiYEcKl7nHwNFwWCrnMMJbVc="
- Status: The certificate is NOT trusted. The certificate issuer is unknown. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
```

I am not well versed in the nuances of the TLS stack, but was directed here from @mcatanzaro so I'm hoping they can fill in the gaps. For context, I am running on Fedora 35, Flatpak version `1.12.2`, and p11-kit version `0.23.22-4.fc35`.

**Comment by mcatanzaro** [comment]
Additional context:

 * freedesktop-sdk configures GnuTLS to use p11-kit as the system trust
 * Note, from the `gnutls-cli` output above: `Processed 0 CA certificate(s).` Zero CA certificates is bad.
 * p11-kit-server appears to be running on the host system
 * We expect empty output from `p11tool --list-tokens` based on [this duplicate report](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1366#note_798369466), both within the flatpak environment and also on the host system. (Kevin, please confirm you see the same.)

Why might `p11tool --list-tokens` return nothing if p11-kit-server is running?

**Comment by kevincianfarini** [comment]
My output is empty as well. 

Something possibly noteworthy. I did not have `libopts.so` available on my machine and had to install `autogen-libopts`. I don't know if that would somehow interfere with `p11-kit-server`.

**Comment by mcatanzaro** [comment]
> Something possibly noteworthy. I did not have libopts.so available on my machine and had to install autogen-libopts. I don't know if that would somehow interfere with p11-kit-server.

I've never heard of libopts, and I don't think it has anything to do with p11-kit? I doubt it would make any difference whether it is installed or not. (I understand it's sometimes tough to know whether certain details may or may not be related to a bug. Why exactly did you need to install libopts?)

**Comment by kevincianfarini** [comment]
In order to run `p11tool --list-tokens`.

**Comment by Zahrun** [comment]
Hey! I am not sure where to post this.

I had a similar issue with some flatpaks giving me ERR_CERT_AUTHORITY_INVALID, invalid certificate errors, eg. Teams, Discord, UngoogledChromium on Kubuntu 21.10. Which made me unable to use them for several days.

I get the same symptoms:
```
gnutls-cli app.slack.com
Processed 128 CA certificate(s).
[...]
flatpak run -d --command=/bin/bash com.discordapp.Discord
gnutls-cli app.slack.com
Processed 0 CA certificate(s).
```

I was randomly wondering today what I had installed with (home)brew and realized that p11-kit, gnutls, ca-certificates had been installed as a dependency of apktool, which reminded me of this issue here.
So on the host machine I get
```
whereis p11-kit
p11-kit: /usr/bin/p11-kit /usr/libexec/p11-kit /usr/share/p11-kit /home/linuxbrew/.linuxbrew/bin/p11-kit /usr/share/man/man8/p11-kit.8.gz
```
Then I tried
```
brew uninstall apktool
brew autoremove
reboot
```
And now my flatpaks are fixed.
It seems that flatpak is taking `/home/linuxbrew/.linuxbrew/bin/p11-kit` instead of the `/usr/bin/p11-kit` (0.23.22-1build1), and that there is an issue with the linuxbrew version of p11-kit (0.24.0).

The issue might be different in your case. Can you run `whereis p11-kit` on your host machine to check if you have different versions installed? Or maybe is your distro-provided version of p11-kit 0.24.0?

Sorry if this message was in the wrong thread.

**Comment by kevincianfarini** [comment]
This seems suspicious for me, too! I will try the mitigation later. 

```
$ whereis p11-kit
p11-kit: /usr/bin/p11-kit /usr/libexec/p11-kit /usr/share/p11-kit /home/linuxbrew/.linuxbrew/bin/p11-kit /usr/share/man/man8/p11-kit.8.gz

```

**Comment by kevincianfarini** [comment]
Doing `brew deps --tree --installed` will help you figure out which dependency has installed `p11-kit` transitively. 

For me, the offender was `flyway`. Anything requiring `openjdk` be installed through `brew` I think will cause issues. 

```
flyway
└── openjdk
    ├── alsa-lib
    ├── cups
    │   ├── krb5
    │   │   ├── openssl@1.1
    │   │   │   └── ca-certificates
    │   │   ├── bison
    │   │   │   └── m4
    │   │   └── gettext
    │   │       ├── libxml2
    │   │       │   ├── readline
    │   │       │   │   └── ncurses
    │   │       │   └── zlib
    │   │       └── ncurses
    │   ├── zlib
    │   └── gnutls
    │       ├── ca-certificates
    │       ├── gmp
    │       ├── guile
    │       │   ├── bdw-gc
    │       │   ├── gmp
    │       │   ├── libffi
    │       │   ├── libtool
    │       │   │   └── m4
    │       │   ├── libunistring
    │       │   ├── pkg-config
    │       │   ├── readline
    │       │   │   └── ncurses
    │       │   └── gperf
    │       ├── libidn2
    │       │   ├── gettext
    │       │   │   ├── libxml2
    │       │   │   │   ├── readline
    │       │   │   │   │   └── ncurses
    │       │   │   │   └── zlib
    │       │   │   └── ncurses
    │       │   └── libunistring
    │       ├── libtasn1
    │       ├── libunistring
    │       ├── nettle
    │       │   └── gmp
    │       ├── p11-kit
    │       │   └── libffi
```

**Comment by kevincianfarini** [comment]
After rebooting, that fixed the problem. Wonderful, thank you @Zahrun. 

Now the question remains, why is the brew installation of `p11-kit` fubar?

**Comment by Zahrun** [comment]
I’m glad we could narrow down the issue.
apktool is also dependent on openjdk in homebrew

When installing homebrew, we have done as part as the install instructions
`echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.profile`
Which at session opening does, among other things, places the brew binaries at the head of PATH:
`export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";`
If we want to change the order in PATH, the file to alter would be `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/shellenv.sh`
For bash, that could be change 
`echo "export PATH=\"${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin\${PATH+:\$PATH}\";"` to 
`echo "export PATH=\"\${PATH+\$PATH}:${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin\";"`

The workaround has the downside of giving the least priority to brew binaries if we have multiple versions of the same executables. Also, brew will automatically revert the change:
```
brew install apktool
Running `brew update --preinstall`...
To restore the stashed changes to /home/linuxbrew/.linuxbrew/Homebrew, run:
  cd /home/linuxbrew/.linuxbrew/Homebrew && git stash pop
```

I think the real issue is that p11-kit fails in its homebrew version. Now, maybe the p11-glue team here can help identify why. Otherwise, the brew team might be able to assist over at https://github.com/Homebrew/homebrew-core/blob/master/Formula/p11-kit.rb

**Comment by kevincianfarini** [comment]
Is there a known certificate issue with p11-kit version `>= 0.24.x`?

**Comment by Zahrun** [comment]
Or maybe it’s due to the compilation configuration option in the brew formula?
```
system "./configure", "--disable-dependency-tracking",
                          "--disable-silent-rules",
                          "--disable-trust-module",
                          "--prefix=#{prefix}",
                          "--sysconfdir=#{etc}",
                          "--with-module-config=#{etc}/pkcs11/modules",
                          "--without-libtasn1"
```

**Comment by mcatanzaro** [comment]
Woooow.

`--disable-trust-module` looks pretty suspicious? I guess that is why you have no certificates available?

Maybe allowing it to override your PATH is not advisable. At least, if you're going to install stuff that conflicts with system binaries, you surely want it to _append_ rather than _prepend_....

**Comment by kevincianfarini** [comment]
Prepend versus append should surely be an issue raised on the Homebrew repo.

**Comment by Zahrun** [comment]
Fixed brew formula merge request sent to the Homebrew repo ;)

It was missing the trust-module.

**Comment by mcatanzaro** [comment]
Thanks Zahrun. Wouldn't have figured this out without you!

Kevin, I think this ticket can be closed now, yes? There doesn't seem to be anything wrong with upstream p11-kit.

**Comment by Zahrun** [comment]
Thanks @mcatanzaro for pointing out the p11-kit in the other issue. I wouldn’t have figured this out without you! ;)
And thanks @kevincianfarini for the good bug reports

**Comment by kevincianfarini** [comment]
Perfect! Thank you everyone!
