### ISSUE TITLE
Wrong minimum meson_version

### ISSUE THREAD

**Issue by Jakuje** [p11-glue/p11-kit#569]
during build with meson 1.2.1 I get the following warning:
```
WARNING: Project specifies a minimum meson_version '>= 0.49' but uses features which were added in newer versions:
 * 0.59.0: {'dep 'intl' custom lookup'}
```
It looks like the minimum version should be bumped or the features from new meson should not be used.

**Comment by ueno** [comment]
0.59 might be too new according to [repology](https://repology.org/project/meson/versions), where Ubuntu 20.04 LTS is at 0.53.2 and CentOS Stream 8 is at 0.58.2.

**Comment by ueno** [comment]
After a closer look, this is caused by `libintl = dependency('intl', required: false)` intended for checking if libintl is available, but interpreted as a [custom dependency](https://mesonbuild.com/Dependencies.html#intl). I guess we could rewrite it with `libintl = cc.find_library('intl', required: false)`. That might require additional check on [appleframeworks](https://mesonbuild.com/Dependencies.html#appleframeworks) on macOS, as libintl (if it is from GNU gettext) might be using it for [locale](https://git.savannah.gnu.org/cgit/gnulib.git/tree/lib/setlocale.c#n40) handling.
